### ISSUE TITLE
Build fails due to XPATH_LIMIT

### ISSUE THREAD

**Issue by tsujiguchitky** [openam-jp/opendj#11]
## Description

Build fails in OpenDJ Configuration API when building in combination with newer release of OpenJDK.

From the following error, it looks like the XPath limit is affecting.

```
[INFO] ------------------------------------------------------------------------
[INFO] Building OpenDJ Configuration API 3.0.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-plugin-versions) @ opendj-config ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-java-version) @ opendj-config ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-maven-version) @ opendj-config ---
[INFO] 
[INFO] --- i18n-maven-plugin:1.4.4-SNAPSHOT:generate-messages (default) @ opendj-config ---
[INFO] Adding source directory: /home/builduser/source/opendj/opendj-config/target/generated-sources/messages
[INFO] AdminMessages.java is up to date
[INFO] ConfigMessages.java is up to date
[INFO] ExtensionMessages.java is up to date
[INFO] ProtocolMessages.java is up to date
[INFO] DsconfigMessages.java is up to date
[INFO] 
[INFO] --- opendj-maven-plugin:3.0.2-SNAPSHOT:generate-config (generate-config) @ opendj-config ---
[INFO] Loading XSLT stylesheets...
java.lang.RuntimeException: XPATH_LIMIT
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.parseTopLevel(Parser.java:1127)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.parseExpression(Parser.java:1074)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.ValueOf.parseContents(ValueOf.java:54)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.SyntaxTreeNode.parseChildren(SyntaxTreeNode.java:430)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Template.parseContents(Template.java:247)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.parseOwnChildren(Stylesheet.java:597)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.parseContents(Stylesheet.java:559)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Import.parseContents(Import.java:131)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.parseOwnChildren(Stylesheet.java:597)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.parseContents(Stylesheet.java:559)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Import.parseContents(Import.java:131)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.parseOwnChildren(Stylesheet.java:597)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.parseContents(Stylesheet.java:559)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Import.parseContents(Import.java:131)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.parseOwnChildren(Stylesheet.java:597)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Stylesheet.parseContents(Stylesheet.java:559)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.Parser.createAST(Parser.java:393)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:469)
	at com.sun.org.apache.xalan.internal.xsltc.compiler.XSLTC.compile(XSLTC.java:557)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl.newTemplates(TransformerFactoryImpl.java:947)
	at org.forgerock.opendj.maven.GenerateConfigMojo.loadStylesheet(GenerateConfigMojo.java:428)
	at org.forgerock.opendj.maven.GenerateConfigMojo.initializeStylesheets(GenerateConfigMojo.java:405)
	at org.forgerock.opendj.maven.GenerateConfigMojo.execute(GenerateConfigMojo.java:199)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
...
ERROR:  'JAXP0801002: the compiler encountered an XPath expression containing '125' operators that exceeds the '100' limit set by 'FEATURE_SECURE_PROCESSING'.'
FATAL ERROR:  'JAXP0801002: the compiler encountered an XPath expression containing '125' operators that exceeds the '100' limit set by 'FEATURE_SECURE_PROCESSING'.'
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OpenDJ Directory Services Project .................. SUCCESS [  0.332 s]
[INFO] OpenDJ Maven Plugin ................................ SUCCESS [  2.150 s]
[INFO] OpenDJ Configuration API ........................... FAILURE [  0.522 s]
[INFO] OpenDJ Commons REST LDAP Gateway ................... SKIPPED
[INFO] OpenDJ Server ...................................... SKIPPED
[INFO] OpenDJ Server Example Plugin ....................... SKIPPED
[INFO] OpenDJ Legacy ...................................... SKIPPED
[INFO] OpenDJ ............................................. SKIPPED
[INFO] OpenDJ DSML Gateway ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.664 s
[INFO] Finished at: 2022-06-29T07:32:05+00:00
[INFO] Final Memory: 44M/1225M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal jp.openam.opendj:opendj-maven-plugin:3.0.2-SNAPSHOT:generate-config (generate-config) on project opendj-config: XSLT configuration transformation failed: JAXP0801002: the compiler encountered an XPath expression containing '125' operators that exceeds the '100' limit set by 'FEATURE_SECURE_PROCESSING'. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :opendj-config
```

## Steps to reproduce

```
$ mvn install -f opendj
```

## Enviroment

* CentOS Linux release 7.9.2009 (Core)
* openjdk version "1.8.0_332" (java-1.8.0-openjdk-1.8.0.332.b09-1.el7_9.x86_64)
* Apache Maven 3.3.9 (rh-maven33-1-18.sc3.el7.x86_64)

**Comment by tsujiguchitky** [comment]
The error occurred in the `opendj-config` project, but `GenerateConfigMojo` that threw the exception exists in `opendj-maven-plugin`.

The OpenDJ build uses `opendj-maven-plugin` to generate Java classes from XML. Perhaps the XML input at this time has exceeded the limits of the JDK.

**Comment by tsujiguchitky** [comment]
JDK 8u331 added XML parser restrictions.

See https://www.oracle.com/java/technologies/javase/8u331-relnotes.html

It seems that `jdk.xml.xpathExprOpLimit` is affecting this error.

**Comment by tsujiguchitky** [comment]
Since `opendj-maven-plugin` works only at build time, I think that the restriction can be relaxed as follows.

```
opendj-maven-plugin/src/main/java/org/forgerock/opendj/maven/GenerateConfigMojo.java
401     private void initializeStylesheets() throws TransformerConfigurationException {
402         getLog().info("Loading XSLT stylesheets...");
403         stylesheetFactory = TransformerFactory.newInstance();
404         stylesheetFactory.setAttribute("jdk.xml.xpathExprOpLimit", "200"); // here
```

**Comment by tsujiguchitky** [comment]
> I think that the restriction can be relaxed as follows.

Oops, I needed to be careful about compatibility.

`TransformerFactory` seems to throw `IllegalArgumentException` if it doesn't support `jdk.xml.xpathExprOpLimit`.
